---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: latest
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-12.04
#  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[platformstack::default]
    attributes:
