---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    openssh:
      server:
        password_authentication: 'yes'
        permit_root_login: 'yes'
    ntp:
      apparmor_enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      iptables:
        allow_ssh_from_world: true
      cloud_monitoring:
        enabled: false
      cloud_backup:
        enabled: false
      omnibus_updater:
        enabled: false

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[platformstack::default]
    attributes:
