---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    ntp:
      apparmor_enabled: false
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_monitoring:
        enabled: false
      cloud_backup:
        enabled: false
      omnibus_updater:
        enabled: false

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[platformstack::default]
    attributes:
