---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: _default
  attributes:
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true
    platformstack:
      cloud_monitoring:
        enabled: false
    rackspace:
      cloudbackup:
        enabled: false

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[platformstack::default]
    attributes:
